In [ ]:
# bibliotecas que necesitaremos 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Carga y vistazo inicial del df

In [ ]:

# pip install -r requirements.txt
# pip install openpyxl

# cargo los datos desde el archivo de Excel (.xlsx)
# El archivo tiene 4 hojas, solo 2 son relevantes para el análisis, el resto son metadatos

# cargaré las hojas "tipos de cambio" y "llegadas de turistas"

# Cargar tipos de cambio (datos diarios)
tc_df = pd.read_excel('tc_turistas.xlsx', sheet_name='tipos de cambio')

# Cargar turistas (datos mensuales) 
turistas_df = pd.read_excel('tc_turistas.xlsx', sheet_name='llegadas de turistas')

# En este caso, no hizo falta hacer "skiprows", ya que los metadatos estaban en hoja aparte

print("Datos cargados exitosamente")
print(f"Tipos de cambio: {tc_df.shape}")
print(f"Turistas: {turistas_df.shape}")

# .shape devuelve una tupla (filas, columnas) del dataframe

Datos cargados exitosamente
Tipos de cambio: (1004, 3)
Turistas: (99, 8)

In [ ]:
# muestro las primeras 5 filas de cada dataset

tc_df.head()

# vemos valores sospechosos, varios NaN, faltaría verificar tipo de dato

       FECHA  DOLAR Oficial  DOLAR Blue
0 2017-06-01          16.25       16.30
1 2017-06-02          16.20       16.32
2 2017-06-03            NaN         NaN
3 2017-06-04            NaN         NaN
4 2017-06-05          16.20       16.34

In [8]:
turistas_df.head()

,anio,mes,date,Bolivia,Brasil,Chile,Paraguay,Uruguay
0,2013,ene,41275,141417.459190,112996.623524,66007.699999,50277.720853,52456.413939
1,2013,feb,41306,95204.256341,161366.098439,62013.313451,52666.951095,41377.875955
2,2013,mar,41334,82862.061107,96727.365114,81096.057038,92714.958474,43728.713276
3,2013,abr,41365,72009.462620,66978.888460,55096.585327,67716.242304,27458.646062
4,2013,may,41395,79131.435938,63886.966089,61641.446807,70544.694702,23592.398421

In [16]:
# vemos la información de los df
print("*"*60)
print("Dataframe Tipos de Cambio")
print("*"*60)
tc_df.info()
print("\n")
print("Nombres de columnas: ", tc_df.columns.tolist())

************************************************************
Dataframe Tipos de Cambio
************************************************************
<class 'pandas.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FECHA          1004 non-null   datetime64[us]
 1   DOLAR Oficial  668 non-null    float64
 2   DOLAR Blue     671 non-null    float64
dtypes: datetime64[us](1), float64(2)
memory usage: 23.7 KB


Nombres de columnas:  ['FECHA', 'DOLAR Oficial', 'DOLAR Blue']

In [17]:
print("*"*60)
print("Dataframe Llegadas de Turistas")
print("*"*60)
turistas_df.info()
print("\n")
print("Nombres de columnas: ", turistas_df.columns.tolist())
print("\n")

************************************************************
Dataframe Llegadas de Turistas
************************************************************
<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anio      99 non-null     int64
 1   mes       99 non-null     str
 2   date      99 non-null     int64
 3   Bolivia   99 non-null     float64
 4   Brasil    99 non-null     float64
 5   Chile     99 non-null     float64
 6   Paraguay  99 non-null     float64
 7   Uruguay   99 non-null     float64
dtypes: float64(5), int64(2), str(1)
memory usage: 6.6 KB


Nombres de columnas:  ['anio', 'mes', 'date', 'Bolivia', 'Brasil', 'Chile', 'Paraguay', 'Uruguay']

In [22]:
# normalizo los nombres de las columnas
tc_df.columns = tc_df.columns.str.strip().str.lower().str.replace(' ', '_')
turistas_df.columns = turistas_df.columns.str.strip().str.lower().str.replace(' ', '_')

print("Columnas:")
print("Dataframe tipos de cambio:", tc_df.columns.to_list())
print("Dataframe turistas:", turistas_df.columns.to_list())

Columnas:
Dataframe tipos de cambio: ['fecha', 'dolar_oficial', 'dolar_blue']
Dataframe turistas: ['anio', 'mes', 'date', 'bolivia', 'brasil', 'chile', 'paraguay', 'uruguay']